### ISSUE TITLE
Issue when running server.js 

### ISSUE THREAD

**Issue by stanleycelestin1** [argallab/RemoteHRI#12]
After running npm install succesffult in the server folder, I am having trouble getting node server.js to work. Each time I run it says that **Error: Cannot find module cors**. What should I do here?

**Comment by deepakgopinath** [comment]
Hi, 

Thanks for pointing this out. You can try `npm install cors' to install the cors package (potentially within the server folder). Apologies as we are still are in the dev phase of this project. All of this will be rectified in the first proper release!

Thanks
Deepak

**Comment by stanleycelestin1** [comment]
Got it to work! It also threw the same error for shelljs. After installing them individually it worked. 
Thank you @deepakgopinath.
